In [1]:
import sys

print(sys.executable)

c:\Users\HP\Desktop\Retail-Analytics-AI-Forecasting\.venv\Scripts\python.exe

In [3]:
import os

file_path = "../data/Retail_Sales_Data.xlsx"

print("File path:")
print(os.path.abspath(file_path))

print("\nFile exists:")
print(os.path.exists(file_path))

File path:
c:\Users\HP\Desktop\Retail-Analytics-AI-Forecasting\data\Retail_Sales_Data.xlsx

File exists:
True

In [5]:
import pandas as pd

# Path to the Excel dataset
file_path = "../data/4877028-Retail_Sales_Data.xlsx"

# Load the Excel file
df = pd.read_excel(file_path, engine="openpyxl")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 73000
Columns: 19

In [6]:
df.head()

,Date,Store_ID,Store_Location,Product_ID,Product_Category,Product_Subcategory,Brand,Unit_Price,Units_Sold,Total_Sales,Discount_Percentage,Revenue,Customer_Type,Payment_Mode,Promotion_Applied,Stock_On_Hand,Store_Rating,Region,Holiday_Flag
0,13-04-2023,STR_104,Chennai,PRD_072,Sports,Athletics,Reebok,29973.06,39,1168949.34,5,1.110502e+06,Returning,Debit Card,Yes,422,4.4,South,0
1,25-10-2024,STR_103,Delhi,PRD_492,Sports,Outdoor,Yonex,46933.78,2,93867.56,15,7.978743e+04,Returning,UPI,No,302,4.1,North,0
2,28-02-2023,STR_107,Kolkata,PRD_958,Groceries,Household,Nestle,39280.28,44,1728332.32,15,1.469082e+06,Returning,Cash,No,184,3.8,East,0
3,16-06-2023,STR_102,Bangalore,PRD_014,Home Appliances,Kitchen,Whirlpool,40439.03,9,363951.27,5,3.457537e+05,New,UPI,Yes,493,3.7,South,0
4,23-05-2024,STR_108,Ahmedabad,PRD_932,Fashion,Women Clothing,Puma,9193.58,4,36774.32,5,3.493560e+04,Returning,Credit Card,No,359,3.5,West,0

In [7]:
print("Column Names:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Column Names:
1. Date
2. Store_ID
3. Store_Location
4. Product_ID
5. Product_Category
6. Product_Subcategory
7. Brand
8. Unit_Price
9. Units_Sold
10. Total_Sales
11. Discount_Percentage
12. Revenue
13. Customer_Type
14. Payment_Mode
15. Promotion_Applied
16. Stock_On_Hand
17. Store_Rating
18. Region
19. Holiday_Flag

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73000 entries, 0 to 72999
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 73000 non-null  object
 1   Store_ID             73000 non-null  str
 2   Store_Location       73000 non-null  str
 3   Product_ID           73000 non-null  str
 4   Product_Category     73000 non-null  str
 5   Product_Subcategory  73000 non-null  str
 6   Brand                73000 non-null  str
 7   Unit_Price           73000 non-null  float64
 8   Units_Sold           73000 non-null  int64
 9   Total_Sales          73000 non-null  float64
 10  Discount_Percentage  73000 non-null  int64
 11  Revenue              73000 non-null  float64
 12  Customer_Type        73000 non-null  str
 13  Payment_Mode         73000 non-null  str
 14  Promotion_Applied    73000 non-null  str
 15  Stock_On_Hand        73000 non-null  int64
 16  Store_Rating         73000 non-null  float64
 17  Region               73000 non-null  str
 18  Holiday_Flag         73000 non-null  int64
dtypes: float64(4), int64(4), object(1), str(10)
memory usage: 15.2+ MB

In [9]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Date                   0
Store_ID               0
Store_Location         0
Product_ID             0
Product_Category       0
Product_Subcategory    0
Brand                  0
Unit_Price             0
Units_Sold             0
Total_Sales            0
Discount_Percentage    0
Revenue                0
Customer_Type          0
Payment_Mode           0
Promotion_Applied      0
Stock_On_Hand          0
Store_Rating           0
Region                 0
Holiday_Flag           0
dtype: int64

In [10]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unit_Price,73000.0,25110.208554,14393.607981,100.110,12728.855000,25071.8000,37557.3375,49999.85
Units_Sold,73000.0,24.894589,14.134824,1.000,13.000000,25.0000,37.0000,49.00
Total_Sales,73000.0,626138.239282,544854.836919,144.700,175985.232500,471357.7200,953986.3800,2447350.08
Discount_Percentage,73000.0,10.010411,7.064131,0.000,5.000000,10.0000,15.0000,20.00
Revenue,73000.0,563476.477603,493890.517322,122.995,157537.656875,422356.4515,857115.5850,2447350.08
Stock_On_Hand,73000.0,274.624712,129.663977,50.000,162.000000,274.0000,387.0000,499.00
Store_Rating,73000.0,4.249421,0.434722,3.500,3.900000,4.2000,4.6000,5.00
Holiday_Flag,73000.0,0.012288,0.110167,0.000,0.000000,0.0000,0.0000,1.00

In [12]:
# Convert Date column to datetime
df['Date'] = pd.to_datetime(
    df['Date'],
    dayfirst=True,
    errors='coerce'
)

print("Date conversion completed.")
print("Date data type:", df['Date'].dtype)
print("Invalid dates:", df['Date'].isna().sum())

Date conversion completed.
Date data type: datetime64[us]
Invalid dates: 0

In [13]:
print("Minimum Date:", df['Date'].min())
print("Maximum Date:", df['Date'].max())

Minimum Date: 2023-01-01 00:00:00
Maximum Date: 2024-12-31 00:00:00

In [14]:
# Clean whitespace from text columns
text_columns = df.select_dtypes(include='object').columns

for column in text_columns:
    df[column] = df[column].str.strip()

print("Text columns cleaned successfully.")

Text columns cleaned successfully.

C:\Users\HP\AppData\Local\Temp\ipykernel_5520\2176399276.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include='object').columns

In [15]:
print("Negative Unit Price:", (df['Unit_Price'] < 0).sum())
print("Negative Units Sold:", (df['Units_Sold'] < 0).sum())
print("Negative Total Sales:", (df['Total_Sales'] < 0).sum())
print("Negative Discount:", (df['Discount_Percentage'] < 0).sum())
print("Discount above 100%:", (df['Discount_Percentage'] > 100).sum())
print("Negative Revenue:", (df['Revenue'] < 0).sum())
print("Negative Stock:", (df['Stock_On_Hand'] < 0).sum())

Negative Unit Price: 0
Negative Units Sold: 0
Negative Total Sales: 0
Negative Discount: 0
Discount above 100%: 0
Negative Revenue: 0
Negative Stock: 0

In [16]:
print("Minimum Store Rating:", df['Store_Rating'].min())
print("Maximum Store Rating:", df['Store_Rating'].max())

Minimum Store Rating: 3.5
Maximum Store Rating: 5.0

In [17]:
print("Store Locations:")
print(df['Store_Location'].unique())

print("\nProduct Categories:")
print(df['Product_Category'].unique())

print("\nCustomer Types:")
print(df['Customer_Type'].unique())

print("\nPayment Modes:")
print(df['Payment_Mode'].unique())

print("\nRegions:")
print(df['Region'].unique())

print("\nPromotion Values:")
print(df['Promotion_Applied'].unique())

print("\nHoliday Values:")
print(df['Holiday_Flag'].unique())

Store Locations:
<ArrowStringArray>
[  'Chennai',     'Delhi',   'Kolkata', 'Bangalore', 'Ahmedabad',    'Mumbai',
      'Pune', 'Hyderabad']
Length: 8, dtype: str

Product Categories:
<ArrowStringArray>
['Sports', 'Groceries', 'Home Appliances', 'Fashion', 'Electronics']
Length: 5, dtype: str

Customer Types:
<ArrowStringArray>
['Returning', 'New']
Length: 2, dtype: str

Payment Modes:
<ArrowStringArray>
['Debit Card', 'UPI', 'Cash', 'Credit Card']
Length: 4, dtype: str

Regions:
<ArrowStringArray>
['South', 'North', 'East', 'West']
Length: 4, dtype: str

Promotion Values:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Holiday Values:
[0 1]

In [18]:
# Save the cleaned dataset

cleaned_file_path = "../data/cleaned_retail_sales.csv"

df.to_csv(cleaned_file_path, index=False)

print("Cleaned dataset saved successfully!")
print("File:", cleaned_file_path)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Cleaned dataset saved successfully!
File: ../data/cleaned_retail_sales.csv
Rows: 73000
Columns: 19

In [19]:
# Verify the cleaned dataset

cleaned_df = pd.read_csv(cleaned_file_path)

print("Cleaned dataset verification:")
print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])
print("Missing values:", cleaned_df.isnull().sum().sum())
print("Duplicate rows:", cleaned_df.duplicated().sum())

Cleaned dataset verification:
Rows: 73000
Columns: 19
Missing values: 0
Duplicate rows: 0

In [20]:
import pandas as pd

# Load cleaned dataset
cleaned_file_path = "../data/cleaned_retail_sales.csv"

df = pd.read_csv(cleaned_file_path)

# Convert Date back to datetime after reading CSV
df['Date'] = pd.to_datetime(df['Date'])

print("Cleaned dataset loaded!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Cleaned dataset loaded!
Rows: 73000
Columns: 19

In [21]:
# Create date-based features

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Month_Name'] = df['Date'].dt.month_name()
df['Quarter'] = df['Date'].dt.quarter
df['Day'] = df['Date'].dt.day
df['Day_of_Week'] = df['Date'].dt.day_name()
df['Week_of_Year'] = df['Date'].dt.isocalendar().week

print("Date features created successfully!")

Date features created successfully!

In [22]:
print("Updated columns:")
print(df.columns.tolist())

Updated columns:
['Date', 'Store_ID', 'Store_Location', 'Product_ID', 'Product_Category', 'Product_Subcategory', 'Brand', 'Unit_Price', 'Units_Sold', 'Total_Sales', 'Discount_Percentage', 'Revenue', 'Customer_Type', 'Payment_Mode', 'Promotion_Applied', 'Stock_On_Hand', 'Store_Rating', 'Region', 'Holiday_Flag', 'Year', 'Month', 'Month_Name', 'Quarter', 'Day', 'Day_of_Week', 'Week_of_Year']

In [23]:
df[['Date', 'Year', 'Month', 'Month_Name',
    'Quarter', 'Day', 'Day_of_Week', 'Week_of_Year']].head(10)

        Date  Year  Month Month_Name  Quarter  Day Day_of_Week  Week_of_Year
0 2023-04-13  2023      4      April        2   13    Thursday            15
1 2024-10-25  2024     10    October        4   25      Friday            43
2 2023-02-28  2023      2   February        1   28     Tuesday             9
3 2023-06-16  2023      6       June        2   16      Friday            24
4 2024-05-23  2024      5        May        2   23    Thursday            21
5 2024-06-02  2024      6       June        2    2      Sunday            22
6 2023-02-22  2023      2   February        1   22   Wednesday             8
7 2024-09-10  2024      9  September        3   10     Tuesday            37
8 2023-02-02  2023      2   February        1    2    Thursday             5
9 2024-05-17  2024      5        May        2   17      Friday            20

In [24]:
feature_file_path = "../data/retail_sales_features.csv"

df.to_csv(feature_file_path, index=False)

print("Feature-engineered dataset saved successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("File:", feature_file_path)

Feature-engineered dataset saved successfully!
Rows: 73000
Columns: 26
File: ../data/retail_sales_features.csv